### ISSUE TITLE
优酷下载失效了，一起研究下

### ISSUE THREAD

**Issue by redstoneleo** [Northxw/Python3_WebSpider#1]
https://github.com/Northxw/Python3_WebSpider/blob/2788461c16da4e651fc9e9654467de2ad128613d/11-Spider_video/youku.py

**Comment by Northxw** [comment]
很乐意给你提供帮助，你可以详细说明你的问题！因为我的文章被简书强制下架了，所以代码也就撤销了。

**Comment by redstoneleo** [comment]
1. 什么文章被简书强制下架了？

2. 之前是我copy别人代码造成的问题，下载没事了。谢谢！
