### ISSUE TITLE
视频信息数量多于视频个数

### ISSUE THREAD

**Issue by SDT110** [Northxw/Python3_WebSpider#3]
您好，请问您有出现保存的视频信息多于视频数量的情况出现吗？

**Comment by Northxw** [comment]
一般情况下是必然现象。毕竟视频下载不是多进程。前一个视频若稍微大一点从而占用带宽很大, 下一个可能会直接被抛弃。

**Comment by SDT110** [comment]
那有什么解决办法吗？您提个思路我自己解决……小白完全没想法

**Comment by SDT110** [comment]
谢谢回复☺️

**Comment by Northxw** [comment]
没有百分百完全对应的。网络环境, 服务器状态, 电脑性能等或多或少都会有所影响。提几个点：滑动时间间隔变长,  设置stream参数,  将视频保存为ogg格式(画质稍微受损）,  提高你的网速等等

**Comment by SDT110** [comment]
好的 谢谢您！
