### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by SDT110** [Northxw/Python3_WebSpider#4]
1、文件名保存的时候可以是描述+抖音ID，这样就不会因为相同的文案造成视频下载失败；
2、我一共尝试了两次，第一次爬了426个视频，视频信息共有427个，通过名称筛选一一对应上只有74个，视频信息中有因为视频链接不同保存了多次重复的。剩下的可能是因为我还添加了地理位置的信息，在爬取过程中有警告有的视频没有这项信息，可能没有保存视频信息；
3、json文件让我吃了点苦头，我修改成这样了
with open('./douyin.json', 'a', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False)
                f.write('\n')

谢谢您的分享！帮了我很大忙！

**Comment by Northxw** [comment]
互相学习啊。按道理来说，视频的title也应该是唯一的。谢谢你的建议。
