### ISSUE TITLE
Cannot establish TLS with client (sni: aweme.snssdk.com): TlsException("(-1, 'Unexpected EOF')",)

### ISSUE THREAD

**Issue by SDT110** [Northxw/Python3_WebSpider#5]
今天突然就不能对抖音抓包了，mitmdump和charles都不能了。。昨天还能的。。。请问有什么解决办法吗？多谢！！试了网易云音乐可以

**Comment by Northxw** [comment]
你好，这个出错原因比较多，没看到你的代码我不好说。提几点可能出错的地方：
（1）手机端代理端口出错（8080和8888别混乱）
（2）网络问题（曾经测试的时候多次因为网络问题出现该报错）
（3）多次重新抓包（点击charles的小扫帚，保证每次都是最新的请求，便于观察）
（4）反爬（我测试时没发现反爬，不知道现在有没有）
可能不够全面，实在不行的话，邮箱联系我，主页有邮箱。

**Comment by SDT110** [comment]
感谢！昨天实在没办法用了安卓模拟器，爬下来了数据，所以我猜是被反爬了？而且发现访问地址发生了一点变化。` url2 = 'https://aweme-hl.snssdk.com/aweme/v1/search/item/'
    url3 = 'https://api-hl.amemv.com/aweme/v1/search/item/'`
但其实我不用代理的时候 手机是可以正常访问的，所以还不知道是什么原因

**Comment by Northxw** [comment]
客气啦，还有一点：注意mitmdump和爬虫的启动顺序，否则手机不能正常访问网页。

**Comment by fakeeeewww** [comment]
> 感谢！昨天实在没办法用了安卓模拟器，爬下来了数据，所以我猜是被反爬了？而且发现访问地址发生了一点变化。` url2 = 'https://aweme-hl.snssdk.com/aweme/v1/search/item/' url3 = 'https://api-hl.amemv.com/aweme/v1/search/item/'`
> 但其实我不用代理的时候 手机是可以正常访问的，所以还不知道是什么原因

你好，我也跟你出现了相同的问题，但是很令人遗憾的是，我在用模拟器代理后，就无法上网了，您有什么解决方法吗？我在这个问题上困扰很久了，谢谢

**Comment by SDT110** [comment]
不好意思啊，已经很久没做这个项目了。应该是抖音设置了使用代理ip无法访问，你可以从这个方向试试。


 
---Original---
From: ***@***.***&gt;
Date: 2021/4/27 18:01:00
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Northxw/Python3_WebSpider] Cannot establish TLS with client (sni: aweme.snssdk.com): TlsException("(-1, 'Unexpected EOF')",) (#5)




  
感谢！昨天实在没办法用了安卓模拟器，爬下来了数据，所以我猜是被反爬了？而且发现访问地址发生了一点变化。 url2 = 'https://aweme-hl.snssdk.com/aweme/v1/search/item/' url3 = 'https://api-hl.amemv.com/aweme/v1/search/item/'
 但其实我不用代理的时候 手机是可以正常访问的，所以还不知道是什么原因
  
你好，我也跟你出现了相同的问题，但是很令人遗憾的是，我在用模拟器代理后，就无法上网了，您有什么解决方法吗？我在这个问题上困扰很久了，谢谢
